### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by ZH3nGsQ** [hanzhu97702/DSNet#3]
Thank you for your excellent work, but I encountered this error while testing with the Indian dataset using **python demo.py --dataset='Indian' --patches=7 --flag_test='test'**:

Train data change to the ratio of train samples: 1
height=145,width=145,band=200
**************************************************
patch is : 7
mirror_image shape : [151,151,200]
**************************************************
x_train shape = (695, 7, 7, 200), type = float64
x_test  shape = (9671, 7, 7, 200), type = float64
**************************************************
y_train: shape = (695,) ,type = int32
y_test: shape = (9671,) ,type = int32
**************************************************
Model Name: conv2d_unmix
Traceback (most recent call last):
  File "demo.py", line 215, in <module>
    main()
  File "demo.py", line 157, in main
    prediction_matrix[total_pos_true[i,0], total_pos_true[i,1]] = pre_u[i] + 1
IndexError: index 9671 is out of bounds for axis 0 with size 9671

**Comment by hanzhu97702** [comment]
The files of 'dataset.py' and 'demo.py' have updated, and the 'label_true_loader' is introduced in the testing phase to output the classification results.
